[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "extract-list"
authors = [
  { name="Tom Björkholm", email="klausuler_linnet0q@icloud.com" },
]
description = "Extract a list from JSON or XML, save to excel, csv, etc."
readme = "README_pypi.md"
requires-python = ">=3.13"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Intended Audience :: Other Audience",
    "Intended Audience :: Developers",
    "Topic :: Office/Business",
    "Typing :: Typed"
]
dynamic = ["dependencies", "version"]

[project.urls]
"Source code" = "https://github.com/tom-bjorkholm/extract-list"
