#! /usr/local/bin/python3
"""Test reading configuration files generated by extract-list 0.2.14."""

# Copyright (c) 2026 Tom Björkholm
# MIT License

from pathlib import Path
import sys
import pytest
from extract_list.config_enums import InFileType, MissingInputForColumn
from extract_list.extract_config import ExtractConfig
from extract_list.xl_migrate_cfg_warn_hook import XlMigrateCfgWarnHook
from .check_capsys import check_capsys


CFG_DIR = Path(__file__).parent / 'backward_compat' / '0.2.14'


def _cfg_names() -> list[str]:
    """Return all old configuration fixture names in stable order."""
    return [path.name for path in sorted(CFG_DIR.glob('*.cfg'))]


def _uses_xml_input(cfg_name: str) -> bool:
    """Return whether the old fixture reads XML input."""
    return '_xml_' in cfg_name


def _uses_xml_output(cfg_name: str) -> bool:
    """Return whether the old fixture writes XML output."""
    return cfg_name.endswith('_X_xml.cfg')


def _expected_format_name(cfg_name: str) -> str:
    """Return current output format name expected for the old fixture."""
    old_format = cfg_name.rsplit('_X_', maxsplit=1)[1].removesuffix('.cfg')
    format_names = {'csv': 'CSV', 'excel': 'Excel', 'json': 'JSON',
                    'txt': 'Plaintxt', 'xml': 'XML'}
    return format_names[old_format]


def _expected_infile_type(cfg_name: str) -> InFileType:
    """Return expected input file type for the old fixture."""
    if _uses_xml_input(cfg_name):
        return InFileType.XML
    return InFileType.JSON


def _expected_main_line(cfg_name: str) -> list[str]:
    """Return expected main line path for the old fixture."""
    if cfg_name.startswith('sw_json_to_rrs_'):
        return ['competitors']
    if cfg_name.startswith('sw_xml_to_rrs_'):
        return ['sailwave-data', 'competitors', 'competitor']
    if cfg_name.startswith('example2_'):
        if _uses_xml_input(cfg_name):
            return ['data', 'customers']
        return ['customers']
    if _uses_xml_input(cfg_name):
        return ['data', 'orders']
    return ['orders']


def _expected_missing(cfg_name: str) -> MissingInputForColumn:
    """Return expected missing-input handling for the old fixture."""
    if cfg_name.startswith('example2_'):
        return MissingInputForColumn.ERROR
    return MissingInputForColumn.EMPTY


def _expected_link_count(cfg_name: str) -> int:
    """Return expected number of linked line specs for the old fixture."""
    if cfg_name.startswith('sw_'):
        return 0
    if cfg_name.startswith('example2_'):
        return 2
    return 1


def _expected_include_key(cfg_name: str) -> bool:
    """Return expected include-key setting for the old fixture."""
    return cfg_name.startswith('example_')


def _assert_desc_file(cfg_path: Path) -> None:
    """Check that the old generated description file exists."""
    desc_path = cfg_path.with_suffix('.txt')
    assert desc_path.is_file()
    desc_text = desc_path.read_text(encoding='utf-8')
    assert 'configuration file' in desc_text


def _assert_common_values(cfg: ExtractConfig, cfg_name: str) -> None:
    """Check values shared by all old configuration fixtures."""
    assert cfg.infile_type == _expected_infile_type(cfg_name)
    assert cfg.output.format_name == _expected_format_name(cfg_name)
    assert cfg.output.character_encoding == 'utf-8'
    assert cfg.main_line.line == _expected_main_line(cfg_name)
    assert cfg.missing_input_for_column == _expected_missing(cfg_name)
    assert cfg.include_key == _expected_include_key(cfg_name)
    assert len(cfg.linked_lines) == _expected_link_count(cfg_name)


def _assert_example_values(cfg: ExtractConfig, cfg_name: str) -> None:
    """Check values specific to the first example family."""
    if not cfg_name.startswith('example_'):
        return
    key_name = 'key-col' if _uses_xml_output(cfg_name) else 'key col'
    assert cfg.column_name_for_key == key_name
    assert cfg.one_output_line_per_main_line
    assert cfg.main_line.columns['What'] == ['items', 'item']
    assert cfg.linked_lines[0].linked_main_column == ['customer']


def _assert_example2_values(cfg: ExtractConfig, cfg_name: str) -> None:
    """Check values specific to the second example family."""
    if not cfg_name.startswith('example2_'):
        return
    column_name = 'Deliver-by' if _uses_xml_output(cfg_name) else 'Deliver by'
    assert not cfg.one_output_line_per_main_line
    assert column_name in cfg.column_order
    assert cfg.linked_lines[1].linked_column == ['for_street']


def _assert_sw_values(cfg: ExtractConfig, cfg_name: str) -> None:
    """Check values specific to the Sailwave-to-RRS family."""
    if not cfg_name.startswith('sw_'):
        return
    sail_col = 'Sail-Number' if _uses_xml_output(cfg_name) else 'Sail Number'
    assert cfg.infile_encoding == 'cp1252'
    assert cfg.linked_lines == []
    assert cfg.main_line.columns[sail_col] == ['compsailno']


@pytest.mark.parametrize('cfg_name', _cfg_names())
def test_read_0214_cfgs(capsys: pytest.CaptureFixture[str],
                        cfg_name: str) -> None:
    """Test that each 0.2.14 config reads and asks users to migrate."""
    cfg_path = CFG_DIR / cfg_name
    _assert_desc_file(cfg_path)
    cfg = ExtractConfig(from_json_filename=cfg_path, stderr_file=sys.stderr,
                        auto_ch_hook=XlMigrateCfgWarnHook())
    _assert_common_values(cfg=cfg, cfg_name=cfg_name)
    _assert_example_values(cfg=cfg, cfg_name=cfg_name)
    _assert_example2_values(cfg=cfg, cfg_name=cfg_name)
    _assert_sw_values(cfg=cfg, cfg_name=cfg_name)
    warning_parts = ['Backward compatibility', 'migrate-cfg',
                     'configuration file to the new format']
    check_capsys(capsys=capsys, in_err=warning_parts)
